# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DemoApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for DemoApp
  pod 'SwiftLocation'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'SwiftMessages'
  pod 'PKHUD'
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'RxDataSources', '~> 3.0'
  pod 'McPicker'
  
  pod 'CorePlot', '~> 2.2'
  pod 'SwiftCharts', '~> 0.6.1'
end
