# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'EntrepriseDemo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for EntrepriseDemo
  pod 'SwiftLocation'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'SwiftMessages'
  pod 'PKHUD'
  pod 'ReachabilitySwift'
  pod 'Spruce'
  pod 'SwiftySound'
  pod 'SwipeCellKit'
  pod 'SRCountdownTimer'
  pod 'KUIPopOver'
  pod 'GoogleMaps'
  pod 'HockeySDK', '~> 5.1.1'
  pod 'Socket.IO-Client-Swift', '~> 13.1.0'
  pod 'RxSwift',    '~> 4.0'
  pod 'RxCocoa',    '~> 4.0'
  pod 'RxDataSources', '~> 3.0'
  target 'EntrepriseDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'EntrepriseDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
